#!/bin/bash

# https://github.com/facebook/react-native/issues/4968#issuecomment-263099638
rm -rf node_modules
rm -rf $TMPDIR/react-* --reset-cache
rm -rf node_modules/react-native/packager/packager.sh --reset-cache
npm cache clean

echo "Remember to 'npm install'"
